### PR TITLE
Fix universal selector in descendant selector

### PR DESCRIPTION
**Pull request by Shraymonks**
Fix parsing of descendant selector when the right selector is the universal selector.

### CODE REVIEW

**Comment by Shraymonks** [comment]
@maxbrunsfeld Can this get looked at?

**Comment by amaanq** [comment]
@Shraymonks what about this?

```css
example|* {
  color: blue;
}
```

**Comment by Shraymonks** [comment]
That would be a separate issue; see #33.

**Comment by amaanq** [comment]
Thanks for the ref link, not too familiar with css

**Pull request merged**
